[target.'cfg(target_family = "wasm")']
rustflags = ["-C", "target-feature=+extended-const,+simd128,+tail-call"]

[target.'cfg(not(target_family = "wasm"))']
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = [
  "-C",
  "target-cpu=native",
  "-C",
  "link-arg=-fuse-ld=wild"
]  # Requires Wild 0.9.0+
